# Generated by Django 5.2.9 on 2025-12-13 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("GP", "General Practitioner"),
                            ("CAR", "Cardiologist"),
                            ("NEU", "Neurologist"),
                            ("PED", "Pediatrician"),
                            ("ORTH", "Orthopedist"),
                            ("DERM", "Dermatologist"),
                            ("PSY", "Psychiatrist"),
                            ("RAD", "Radiologist"),
                            ("SUR", "Surgeon"),
                            ("OTH", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("hospital", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
